

export enum ActionTypes {
  SET_AUTH_TOKEN = 'SET_AUTH_TOKEN',
  SET_APP_MODE = 'SET_APP_MODE',
  SET_STORY_TOGGLE_ACTIVE = 'SET_STORY_TOGGLE_ACTIVE',
  SET_SELECTED_STORY = 'SET_SELECTED_STORY',
  SET_WDS_RESPONSE = 'SET_WDS_RESPONSE',
  SET_LOADING_STATE = 'SET_LOADING_STATE',
  SET_TAOPTIONS_STATE = 'SET_TAOPTIONS_STATE',
  RECEIVE_WDS_RES = 'RECEIVE_WDS_RES',
  SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER',
  SET_KEYS_ERROR = 'SET_KEYS_ERROR',
  SET_NOTIFICATION = 'SET_NOTIFICATION'

}

export * from './action-creators'
export * from './async'
